version: "3"

services:
  bitai-flowise:
    image: flowiseai/flowise:latest
    restart: always
    environment:
      - PORT=${PORT}
      - FLOWISE_USERNAME=${FLOWISE_USERNAME}
      - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
      - DEBUG=${DEBUG}
      - DATABASE_PATH=${DATABASE_PATH}
      - APIKEY_PATH=${APIKEY_PATH}
      - SECRETKEY_PATH=${SECRETKEY_PATH}
      - FLOWISE_SECRETKEY_OVERWRITE=${FLOWISE_SECRETKEY_OVERWRITE}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_PATH=${LOG_PATH}
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ~/.bitai_flowise:/root/.flowise
    command: /bin/sh -c "sleep 3; flowise start"